# Generated by Django 3.1.1 on 2020-09-21 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlistings',
            options={'verbose_name': 'Auction Listing'},
        ),
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name': 'Bid'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='url',
            field=models.CharField(default='https://icon-library.com/images/products-icon-png/products-icon-png-25.jpg', max_length=2000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
