# Generated by Django 3.1.1 on 2020-09-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200921_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
